---
title: "scCODA.Rmd"
output: html_document
date: "2024-05-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# scCODA: Compositional Analysis of Single-Cell Data (Pre-processing)

# Load libraries 
```{r}
library(dplyr)
library(Seurat)
library(SeuratObject)
library(hdf5r)
library(ggplot2)
library(tidyr)
library(fgsea)
library(SeuratData)
library(SeuratDisk)
```

# Load in data (seurat object)
```{r}
GEX_ATAC_seur <- readRDS(here::here("Data", "GEX_ATAC_Seur.rds"))
```

# Add meta data to run scCODA analysis
```{r}

# Create a column in metadata called SampleID with same info as orig.ident 
GEX_ATAC_seur@meta.data$SampleID <- GEX_ATAC_seur@meta.data$orig.ident

# Create a column in metadata called cell_type with cell types in cluster_annotations (csv can be found in clustering_and_annotation folder) 

cell_types <- c("CB Granule Glut","Oligo NN", "PGRN-PARN-MDRN Hoxb5 Glut", "Endo NN", "Bergmann NN", "Astro-CB NN", "CB PLI Gly-Gaba", "CBX MLI Megf11 Gaba", "SPVI-SPVC Sall3 Nfib Gly-Gaba", "SPVI-SPVC Tlx3 Ebf3 Glut", "Astro-NT NN", "CBX MLI Cdh22 Gaba", "VLMC NN", "OPC NN", "PG-TRN-LRN Fat2 Glut", "PARN-MDRNd-NTS Gbx2 Gly-Gaba", "MY Lhx1 Gly-Gaba",  "SPVI-SPVC Sall3 Lhx1 Gly-Gaba", "DCO UBC Glut",  "CBX Purkinje Gaba" , "CBX Golgi Gly-Gaba")

GEX_ATAC_seur@meta.data$cell_type <- NA
GEX_ATAC_seur@meta.data$cell_type <- factor(GEX_ATAC_seur@meta.data$cell_type, levels = cell_types)

```

# Save seurat object as h5ad for sccoda analysis in python 
```{r}
# v5 of seurat makes the RNA assay at assayv5 but if you need to convert to anndata for sccoda it needs to be "assay" and not assayv5 hence run: 
GEX_ATAC_seur@assays$RNA <- as(object = GEX_ATAC_seur@assays$RNA, Class = "Assay")

# Save object as h5ad for input into sccoda 
SaveH5Seurat(GEX_ATAC_seur, filename = here::here("Data", "GEX_ATAC_scCODA.h5Seurat"))
Convert(here::here("Data", "GEX_ATAC_scCODA.h5Seurat"), dest = "h5ad", overwrite = TRUE)
```

