---
title: "sccoda"
output: html_document
date: "2023-10-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# scCODA: Compositional Analysis for Single-Cell Dataset 

## Import libs
```{python}
import warnings
warnings.filterwarnings("ignore")

import mudata as mu
import matplotlib.pyplot as plt
import pertpy as pt
```


## Import libs 
```{python setup}
# Imports
import pandas as pd
import matplotlib.pyplot as plt
import anndata as ad
import warnings
#from pertpy.sccoda.util import cell_composition_data as dat
#from sccoda.util import data_visualization as viz

#import sccoda.datasets as scd

warnings.filterwarnings("ignore")
```

## Import data 
```{python read_ad}
adata = ad.read_h5ad("GEX_ATAC_scCODA.h5ad")
print(adata)

```

## Change saline to "Control" as per requirements of scCODA 
```{python}
def control_fun(x):
    if x == "Saline":
      return "Control"
    else:
     return "Fentanyl"

adata.obs['condition'] = adata.obs['condition'].apply(control_fun)

```


# run SCCODA
```{python}
sccoda_model = pt.tl.Sccoda()
sccoda_data = sccoda_model.load(adata, type="cell_level", generate_sample_level=True, cell_type_identifier="aba_classification", sample_identifier="SampleID", covariate_obs=["condition", "sex", "aba_classification"])
print(sccoda_data)
print(sccoda_data["coda"].X)
print(sccoda_data["coda"].obs)
```

## How fentanyl affects cell composition 
```{python}
# Select saline and fentanyl data
sccoda_data.mod["coda_fent"] = sccoda_data["coda"][sccoda_data["coda"].obs["condition"].isin(["Control", "Fentanyl"])].copy()
print(sccoda_data["coda_fent"])
```

```{python}
pt.pl.coda.boxplots(sccoda_data, modality_key="coda_fent", feature_name="condition", add_dots=True)
plt.show()
```

```{python}
# Model set up and inference 

sccoda_data = sccoda_model.prepare(sccoda_data, modality_key="coda_fent", formula="condition", reference_cell_type="automatic")
sccoda_data["coda_fent"]
```

```{python}
# Run MCMC
sccoda_model.run_nuts(sccoda_data, modality_key="coda_fent")
sccoda_data["coda_fent"]
```

```{python}
sccoda_model.set_fdr(sccoda_data, modality_key="coda_fent", est_fdr=0.05)
```

## Save condition[T.fentanyl] as a csv 
```{python}
df = sccoda_data["coda_fent"].varm['effect_df_condition[T.Fentanyl]'] 
df.to_csv('fent_final.csv', index=False)
```

```{python}
#Result Interpretation 
sccoda_model.summary(sccoda_data, modality_key="coda_fent")
# Save summary?
sim_results = sccoda_model.summary(sccoda_data, modality_key="coda_fent")
```

```{python}
sccoda_model.credible_effects(sccoda_data, modality_key="coda_fent")
```

```{python}
# Stacked barplot for the levels of "Condition"
pt.pl.coda.stacked_barplot(sccoda_data, modality_key="coda_fent", feature_name="condition")
plt.show()
plt.savefig('stacked_barplot.png', bbox_inches='tight')
```

## Plot significant cell types with saved CSV

# Load libraries 
```{r}
library(tidyverse)
library(ggplot2)
```

# Load csv 
```{r}
df <- read.csv(here::here("Data", "fent_final.csv"))
```

```{r}
# Cell type names
names <- c("Astro-CB NN", "Astro-NT NN", "Bergmann NN", "CB Granule Glut", "CB PLI Gly-Gaba", "CBX Golgi Gly-Gaba", "CBX MLI Cdh22 Gaba", "CBX MLI Megf11 Gaba", "CBX Purkinje Gaba", "DCO UBC Glut", "Endo NN", "MY Lhx1 Gly-Gaba", "OPC NN", "Oligo NN", "PARN-MDRNd-NTS Gbx2 Gly-Gaba", "PG-TRN-LRN Fat2 Glut", "PGRN-PARN-MDRN Hoxb5 Glut", "SPVI-SPVC Sall3 Lhx1 Gly-Gaba", "SPVI-SPVC Sall3 Nfib Gly-Gaba", "SPVI-SPVC Tlx3 Ebf3 Glut", "VLMC NN") 
           
```

```{r}
# code to generate plot 
p <- df %>%
  dplyr::filter(Cell.Type %in% 6:17) %>%
  mutate(names = factor(names[6:17], levels = unique(names[6:17]))) %>%
  ggplot(aes(x = names, y = log2.fold.change, fill = names)) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = c('#98DF8A', '#D62728', '#FF9896', '#9467BD', '#C5B0D5', 
                               '#8C564B', '#D2B48C', '#FF1493', '#FFB6C1', 
                               '#A9A9A9', '#D3D3D3', '#6B8E23'), length(unique(names[6:17]))) +
  guides(fill = guide_legend(title = "Cell Type")) + 
  labs(fill = "Cell Type", x = "Cell Type", y = "Log2-fold change") +
  ggtitle("Condition[T.fentanyl]") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

print(p)
```



