---
title: "cell-cell_communication.Rmd"
output: html_document
date: "2024-05-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# ScDiffCom: Differential analysis of cell-cell interactions

## Load libraries 
```{r}
library(Seurat)
library(scDiffCom)
library(data.table)
library(ggplot2)
library(future)
```

## Load data 
```{r}
seurat_obj <- readRDS("/Users/rishikadaswani/Desktop/rds/GEX_ATAC_Seur.rds")
```

## Add meta data 
```{r}
# Add cell types to meta-data 
cell_type <- Idents(object = seurat_obj)
names(cell_type) <- colnames(x = seurat_obj)
seurat_obj <- AddMetaData(
  object = seurat_obj,
  metadata = cell_type,
  col.name = 'cell_type'
)

# Add condition to meta-data
drug = rep(c("Saline", "Fentanyl", "Fentanyl", "Saline"), c(4567, 444, 2466, 1284))
names(drug) <- colnames(x = seurat_obj)
seurat_obj <- AddMetaData(
  object = seurat_obj,
  metadata = drug, 
  col.name = 'drug')


plan(sequential)
```

## JoinLayers function to join the layers within the seurat object 
```{r}
seurat_obj[["RNA"]] <- JoinLayers(seurat_obj[["RNA"]])
```

## Run differential analysis with default parameters 
```{r}
scdiffcom_object <- run_interaction_analysis(
  seurat_object = seurat_obj,
  LRI_species = "rat",
  seurat_celltype_id = "cell_type",
  seurat_condition_id = list(
    column_name = "drug",
    cond1_name = "Saline",
    cond2_name = "Fentanyl"
  )
)
```

## CCIs 
```{r}
# Retrieve and display all detected CCIs
CCI_detected <- GetTableCCI(scdiffcom_object, type = "detected", simplified = TRUE)

# Number of CCIs per regulation type (here with age)
table(CCI_detected$REGULATION)
## DOWN  FLAT   NSC    UP 
  # 134   132  70      4 


# Retrieve the ORA results
ORA_results <- GetTableORA(scdiffcom_object, categories = "all", simplified = TRUE)

# Categories available
names(ORA_results)
## [1] "LRI"               "LIGAND_COMPLEX"    "RECEPTOR_COMPLEX" 
## [4] "ER_CELLTYPES"      "EMITTER_CELLTYPE"  "RECEIVER_CELLTYPE"
## [7] "GO_TERMS"          "KEGG_PWS"
```

## Plot CCIs 
```{r}
ggplot(
  CCI_detected,
  aes(
     x = LOGFC,
     y = -log10(BH_P_VALUE_DE + 1E-2),
     colour = REGULATION
  )
) + geom_point(
) + scale_colour_manual(
  values = c("UP" = "red", "DOWN" = "blue", "FLAT" = "green", "NSC" = "grey")
) + xlab(
  "log(FC)"
) + ylab(
  "-log10(Adj. p-value)"
)
```

## Plot the most over-represented up-regulated LRIs
```{r}

# PlotORA returns a ggplot object that you can further optimize (e.g. here to place the legend)
PlotORA(
  object = scdiffcom_object,
  category = "LRI",
  regulation = "UP"
) + theme(
  legend.position = c(0.85, 0.4),
  legend.key.size = unit(0.4, "cm")
)
```

## Build Network of cell-cell communications 
```{r}
BuildNetwork(
  object = scdiffcom_object
)

```


