---
title: "Diff_Exp_Peaks.Rmd"
output: html_document
date: "2024-05-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Differential Expression Analysis of Peaks using Limma Voom
## In order to get the top table we ran the R script on an HPC due to large number of fragments.

## Load libraries 
```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(EnhancedVolcano)
library(gridExtra)
```

```{r}
## Load data 
atac <- readRDS("/Users/rishikadaswani/Desktop/Fentanyl_Multiomics/Data/ATAC_signac.rds")

## Extract counts 
eset <- atac@assays$RNA@counts
ids <- unlist(sapply(strsplit(colnames(eset), "_"), function(i) i[[1]]))
sex <- factor(atac@meta.data$sex, levels = c("Male", "Female"))
drug <- factor(atac@meta.data$drug, levels = c("Saline", "Fentanyl"))
cell_labels <- atac@meta.data$celltype

# Remove the specific cell type
excluded_cell_type <- "Ex_Onecut3_Spag16_3"
cell_labels <- cell_labels[cell_labels != excluded_cell_type]
eset <- eset[, cell_labels != excluded_cell_type]

eset <- as.matrix(eset)
library(parallel)
cl <- makeCluster(detectCores())
clusterExport(cl, c("cell_labels", "sex", "drug", "eset"))
top <- parLapply(cl, names(table(cell_labels)), function(cell){
  library(limma);
  cat(cell, fill = TRUE)
  keep <- cell_labels %in% cell
  counts <- eset[1:15, keep]
  dat <- data.frame(sex = sex[keep],
                    drug = drug[keep],
                    subj = gsub("_.*", "", colnames(counts)))
  
  design <- model.matrix(~sex*drug, data = dat)
  vobj_tmp <- voom(counts, design, plot = FALSE)
  dupcor <- duplicateCorrelation(vobj_tmp, design, block = dat$subj)
  vobj <- voom(counts, design, plot = FALSE, block = dat$subj, correlation = dupcor$consensus)
  dupcor <- duplicateCorrelation(vobj, design, block = dat$subj)
  fitDupCor <- lmFit(vobj, design, block = dat$subj, correlation = dupcor$consensus)
  fitDupCor <- eBayes(fitDupCor)
  top_FvsM <- topTable(fitDupCor, coef = "sexFemale", adjust.method = "BH", number = nrow(fitDupCor))
  top_FvsM$comparison <- "Female_vs_Male"
  top_FvsM$gene <- rownames(top_FvsM)
  top_SvsF <- topTable(fitDupCor, coef = "drugFentanyl", adjust.method = "BH", number = nrow(fitDupCor))
  top_SvsF$comparison <- "Saline_vs_Fentanyl"
  top_SvsF$gene <- rownames(top_SvsF)
  top_int <- topTable(fitDupCor, coef = "sexFemale:drugFentanyl", adjust.method = "BH", number = nrow(fitDupCor))
  top_int$comparison <- "drug x sex interaction"
  top_int$gene <- rownames(top_int)
  top <- rbind(top_FvsM, top_SvsF, top_int)
  top$cell <- cell
  top }) 
stopCluster(cl)

top <- Reduce("rbind", top)
```



## load top table (gene activity top table and atac fragments)
```{r}
top_ga <- readRDS("/Users/rishikadaswani/Desktop/top_atac_signac_final.rds")
top_atac <- readRDS("/Users/rishikadaswani/Desktop/top_atac_updated.rds")
```

## Filter top table for only drug and sex interaction 
```{r}
top_atac_dxs <- top_atac %>% dplyr::filter(top_atac$comparison == "drug x sex interaction")
```

## Find closest genes to peaks
```{r}
# step 1: run closest feature that gives you the closest genes using the regions from atac object 
closest_genes <- ClosestFeature(atac, regions = granges(atac))

# step 2: filter gene activity top table to get highly expressed genes 
highly_expressed_genes <- top_ga[top_ga$adj.P.Val < 0.01, "gene"]

# Step 3: match closest genes with highly expressed genes 
highly_expressed_closest_genes <- closest_genes[closest_genes$gene %in% highly_expressed_genes, ]

# Step 4: identify differentially expressed peaks from top_atac. The fragments are in the column labelled "gene" but these are fragments. 
differentially_expressed_peaks <- top_atac[top_atac$adj.P.Val < 0.01, "gene"]

# Step 5: Combine the information to obtain a data frame which shows highly expressed peaks connected to which highly expressed genes 
# Merge highly expressed closest genes with differentially expressed peaks
result <- merge(highly_expressed_closest_genes, top_atac, by.x = "gene", by.y = "gene")

# Filter for peaks that are differentially expressed by adjusted p-value
result <- result[result$peak %in% differentially_expressed_peaks, ]




Inh_Gata3_Ccdc180_2 <- top_atac_dxs[top_atac_dxs$cell == "Inh_Gata3_Ccdc180_2" & top_atac_dxs$logFC < 3, "gene"]
Endo_Flth1 <- top_atac_dxs[top_atac_dxs$cell == "Endo_Flt1_Lrg1_1" & top_atac_dxs$logFC < 3, "gene"]
Ex_Tfap2b <- top_atac_dxs[top_atac_dxs$cell == "Ex_Tfap2b_Ccdc172_Calcr" & top_atac_dxs$logFC < 3, "gene"]
Ex_C1ql4 <- top_atac_dxs[top_atac_dxs$cell == "Ex_C1ql4_Drd1_3" & top_atac_dxs$logFC < 3, "gene"]

closest_genes_Inh_Gata3 <- ClosestFeature(atac, regions = Inh_Gata3_Ccdc180_2)
closest_genes_Endo_Flth1 <- ClosestFeature(atac, regions = Endo_Flth1)
closest_genes_Ex_Tfap2b <- ClosestFeature(atac, regions = Ex_Tfap2b)
closest_genes_Ex_C1ql4 <- ClosestFeature(atac, regions = Ex_C1ql4)

```
