---
title: "Libra_demo.Rmd"
output: html_document
date: "2024-05-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(Libra)
```


## Libra with demo dataset 
```{r}
data("hagai_toy")
```

```{r}
head(hagai_toy@meta.data)
```


```{r}
DE = run_de(hagai_toy)
head(DE)

```

```{r}
DE = run_de(hagai_toy, de_family = 'mixedmodel', de_method = 'linear', de_type = 'LRT')
head(DE)
```

## Libra with our dataset 
```{r}
data <- readRDS("/Users/rishikadaswani/Desktop/rna_demo.rds")
```

## Add cell types
```{r}
cell_type <- Idents(data)
data <- AddMetaData(data, metadata = cell_type, col.name = "cell_type")
```

## Add "replicates column" which is the sample ids 
```{r}
replicates <- demo_10x$ids
data <- AddMetaData(data, metadata = replicates, col.name = "replicate")
```

## Run `run_de` , and inspect the differential expression 
```{r}
DE = run_de(data, meta = meta, cell_type_col = "cell_type", label_col = "drug", de_family = "mixedmodel", de_method = "linear")
head(DE)
```

```{r}
saveRDS(data, file = "rna_metadata.rds")
```


