---
title: "scCODA.Rmd"
output: html_document
date: "2024-05-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# scCODA: Compositional Analysis of Single-Cell Data (Pre-processing)

# Load libraries 
```{r}
library(dplyr)
library(Seurat)
library(SeuratObject)
library(hdf5r)
library(ggplot2)
library(tidyr)
library(fgsea)
library(SeuratData)
library(SeuratDisk)
```

# Load in data (seurat object)
```{r}
GEX_ATAC_seur <- readRDS("/Users/rishikadaswani/Desktop/Fentanyl_Multiomics/Data/GEX_ATAC_Seur.rds")
```

# Add meta data to run scCODA analysis
```{r}
demo_10x <- data_frame(ids = c("r3", "r4", "r15", "r16"),
                       condition = c("saline", "fentanyl", "fentanyl", "saline"), 
                       sex = c("Male", "Male", "Female", "Female"))

GEX_ATAC_seur@meta.data <- left_join(GEX_ATAC_seur@meta.data, demo_10x, by = c("orig.ident" = "ids"))

# Create a column in metadata called SampleID with same info as orig.ident 
GEX_ATAC_seur@meta.data$SampleID <- GEX_ATAC_seur@meta.data$orig.ident

# Create a column in metadata called cell_type with cell types in cluster_annotations (csv can be found in clustering_and_annotation folder) 

cell_types <- c("Inh_Gata3_Ccdc180_2","Ex_Ebf2_Fzd9_3","Ex_C1ql4_Drd1_3","Ex_Onecut3_Spag16_3","Ex_Fbxo40_Kcnk5_1","Fibro_Eya2_Ccdc192_2","Ex_C1ql4_Prdm6","Ex_Plekhg1_Nox4_Kcp_2","Inh_Frm7_Otop1_1","Ex_Ebf2_Layn","Ex_Tfap2b_Ccdc172_Calcr","Endo_Flt1_Lrg1_1","Endo_Flt1_Ssu2_1","Ex_Fibcd1_Psrc1_4","Ex_Crym_Odad2_Fos","Ex_Sim1_Aox3_1","Ex_Ebf2_Crhr2_1")

GEX_ATAC_seur@meta.data$cell_type <- NA
GEX_ATAC_seur@meta.data$cell_type <- factor(GEX_ATAC_seur@meta.data$cell_type, levels = cell_types)
```

# Save seurat object as h5ad for sccoda analysis in python 
```{r}
# Save object as h5ad for input into sccoda 
SaveH5Seurat(GEX_ATAC_seur, filename = here::here("Data", "GEX_ATAC_scCODA.h5Seurat"))
Convert("/Users/rishikadaswani/Desktop/Fentanyl_Multiomics/Data/GEX_ATAC_scCODA.h5Seurat", dest = "h5ad")
```

