---
title: "spatial_clustering"
output: html_document
date: "2024-07-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Spatial clustering of spatial data using BayesSpace 

## Load libraries 
```{r}
library(BayesSpace)
library(ggplot2)
library(SingleCellExperiment)
library(scran)
library(scater)
library(dplyr)
library(Seurat)
library(dbplyr)
library(tidyverse)
library(reticulate)
library(patchwork)
```

## Load sfe object from svg analysis 
```{r}
sfe <- readRDS(here::here("Data", "sfe.rds"))
```

## Convert sfe to sce for BayesSpace analysis 
```{r}
set.seed(100)
sce.combined <- SingleCellExperiment(
  assays = list(counts = counts(sfe)),
  rowData = rowData(sfe),
  colData = colData(sfe))
colData(sce.combined)$row <- spatialCoords(sfe)[, "CenterX_global_px"]
colData(sce.combined)$col <- spatialCoords(sfe)[, "CenterY_global_px"]
fov_ann <- read.csv("Data/fov_annotations.csv", row.names = 1)
colData(sce.combined)$sample_id <- fov_ann[colData(sce.combined)$fov, "id"]
colData(sce.combined)$drug <- fov_ann[colData(sce.combined)$fov, "drug"]
sce.combined <- scuttle::addPerCellQC(sce.combined)

```

## Quality Control 
```{r}
par(mfrow = c(1, 2))
hist(colData(sce.combined)$sum)
hist(colData(sce.combined)$detected)
# remove combined set of low-quality spots
sce.combined <- sce.combined[, !(colData(sce.combined)$sum < 10 |
                                   colData(sce.combined)$detected < 5)]
```

## Pre-processing the data 
```{r}
sce.combined = spatialPreprocess(sce.combined, platform="ST", assay.type = "counts",
                                 n.PCs=7, n.HVGs=500, log.normalize=FALSE) 

sce.combined = runUMAP(sce.combined, dimred = "PCA")
colnames(reducedDim(sce.combined, "UMAP")) = c("UMAP1", "UMAP2")

ggplot(data.frame(reducedDim(sce.combined, "UMAP")), 
       aes(x = UMAP1, y = UMAP2, color = factor(sce.combined$sample_id))) +
  geom_point(size = 0.7) +
  labs(color = "Sample") +
  theme_bw()
```

## Clustering 
```{r}
# selecting the number of clusters 
sce.combined <- qTune(sce.combined, qs=seq(2, 10), platform="ST", d=7)
qPlot(sce.combined)

# clustering with BayesSpace 
sce.combined = spatialCluster(sce.combined, 
                              use.dimred = "PCA", 
                              q = 9, nrep = 1000,
                              burn.in = 10,
                              platform = "ST") #use HARMONY

# visualizing spatial clusters 
clusterPlot(sce.combined,
            label="spatial.cluster") + #make sure no overlap between samples
  labs(fill = "Sample", title = "Offset check")

sce.combined = spatialCluster(sce.combined, use.dimred = "PCA", q = 7, nrep = 1000, burn.in = 100) #use HARMONY

clusterPlot(sce.combined, color = NA) + #plot clusters
  labs(title = "BayesSpace joint clustering")
```


## MapMyCells to add cell type labels 
```{r}
# library(reticulate)
# use_condaenv(condaenv = '/Users/rishikadaswani/anaconda3/envs/cellanno', required = TRUE)
# 
# library(anndata)
# minimal_adata <- t(counts(sce.combined))
# ad <- AnnData(
#   X = minimal_adata,
#   obs = data.frame(group = rownames(minimal_adata), row.names = rownames(minimal_adata)),
#   var = data.frame(type = colnames(minimal_adata), row.names = colnames(minimal_adata))
# )
# write_h5ad(ad,here::here('rna_fent_counts.h5ad'), compression='gzip')
```

```{r}
# load input from above 
cellann0 <- read.csv(here::here("Data", "rna_fent_counts_10xWholeMouseBrain(CCN20230722)_HierarchicalMapping_UTC_1721032925823", "rna_fent_counts_10xWholeMouseBrain(CCN20230722)_HierarchicalMapping_UTC_1721032925823.csv"), header = FALSE)
cellann <- cellann0[-c(1:5), ]
colnames(cellann) <- as.character(cellann0[5,])
cc <- cellann$class_name
names(cc) <- cellann$cell_id

colData(sce.combined)$celltype <- cc[rownames(colData(sce.combined))]

# plot spatial clusters 
colData(sce.combined) %>% 
  as.data.frame() %>% 
  ggplot(aes(x = row, y = col, color = factor(spatial.cluster))) +
  geom_point(size=0.5) +
  facet_wrap(~sample_id, scales = "free") +
  theme(legend.position = "bottom")
```


```{r}
## plot logFC by spatial cluster
drug0 <- fov_ann %>% 
  group_by(id, drug, sex) %>% 
  dplyr::slice(1)
drug <- factor(drug0$drug, levels = c("Saline", "Fentanyl"))
names(drug) <- drug0$id

b=colData(sce.combined) %>% 
  as.data.frame()  %>%
  dplyr::select(spatial.cluster, sample_id, celltype) %>% 
  group_by(spatial.cluster, sample_id, celltype) %>%
  summarise(n = n()) %>%
  spread(sample_id, n)
c = na.omit(b)

sig_spatial <- c %>% 
  group_by(spatial.cluster, celltype) %>% 
  nest() %>% 
  mutate(pval = purrr::map(data, ~{
    x <- as.numeric(.)
    coef(summary(lm(x~drug[names(.)])))[2, "Pr(>|t|)"]
  })) %>% 
  unnest(pval) %>% 
  arrange(pval) %>% 
  mutate(adjpval = p.adjust(pval, "BH")) %>% 
  mutate(sig = -log10(pval))

d0 = sig_spatial %>% 
  dplyr::select(spatial.cluster, celltype, adjpval) %>% 
  spread(spatial.cluster, adjpval, fill = 1)

d <- as.data.frame(d0[, -1])
rownames(d) <- sapply(strsplit(d0$celltype, " "), function(i) paste(i[-1], collapse = " "))
pvalHeatmap(as.matrix(d))
```

```{r}
coldata <- colData(sce.combined) %>% 
  as.data.frame 
coldata$drug = drug[coldata$sample_id]
coldata %>% 
  mutate(drug_id = paste(drug, as.character(sample_id), sep="_"),
         spatial_cluster = factor(spatial.cluster)) %>% 
  ggplot(aes(x = row, y = col, color = spatial_cluster)) +
  geom_point() +
  facet_wrap(~drug_id, scales = "free") +
  theme(legend.position = "bottom") +
  xlab("x coordinate") +
  ylab("y coordinate")

colData(sce.combined) %>% 
  as.data.frame() %>% 
  filter(spatial.cluster %in% c("4")) %>% 
  filter(celltype %in% c("03 OB-CR Glut", "23 P Glut")) %>% 
  ggplot(aes(x = row, y = col, color = factor(celltype))) +
  geom_point() +
  facet_wrap(~sample_id, scales = "free") +
  theme(legend.position = "bottom")

```

## save sce as an rds object 
```{r}
saveRDS(sce.combined, file = here::here("Data", "sce.rds"))
```

